<?php
/**
* @file
* A description of what your module does.
*/

function hello_init(){

    drupal_set_message("Hello");
}


/*function hello_menu(){

    $items=array();
    $items['hellopage']=array(
'title'=>'My First Drupal Page',
    'description'=>'my first description',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('hello_showHelloForm'),
        'access callback'=>'user_access',
        'access arguments'=>array('access content'),
        'type'=>MENU_NORMAL_ITEM

    );
    return $items;
}

function hello_showHelloForm(){

    $form=array();

    $form['name']=array(
        '#type'=>'textfield',
        '#title'=>'Enter Your Name Dude!'

    );

    return $form;
}
*/

?>