<?php
/**
* @file
* A description of what your module does.
*/



function demo_init() {
drupal_set_message("hello again");
}

function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for demo  module.'),
    ),
  );
}


function demo_node_view($node, $view_mode, $langcode){
  krumo($node);
  //debug($node);
}

function demo_showHelloForm(){
  $form=array();
  $form['name']=array(
    '#type'=>'textfield',
    '#title'=>'Enter You Name'
  );

  $form['submit']=array(
    '#type'=>'submit',
    '#value'=>'submit'
  );
  return $form;
}



/**
 * Implements hook_menu().
 */
function demo_menu() {
  $items['demo'] = array(
    'title' => 'Venky Demo Page',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('demo_showHelloForm'),
    'access callback'=> 'user_access',
    'access arguments'=> array('access content'),
    'type'=>MENU_NORMAL_ITEM
   // 'access arguments' => array('access content'),
    //'type' => MENU_SUGGESTED_ITEM,
  );
  $items['demo/feed'] = array(
    'title' => 'Example RSS feed',
  //  'page callback' => 'example_feed',
 //   'access arguments' => array('access content'),
    //'type' => MENU_CALLBACK,
  );

  return $items;
}

